'use strict';
(()=>{
 const slides=[...document.querySelectorAll('.slide')];let current=0;
 const $=id=>document.getElementById(id);
 function show(n,hash=true){current=Math.max(0,Math.min(slides.length-1,n));slides.forEach((s,i)=>s.hidden=i!==current);$('counter').textContent=current===12?'부록':`${current+1} / 12`;$('slide-label').textContent=slides[current].dataset.title;$('notes-content').textContent=slides[current].querySelector('.notes').textContent;$('previous').disabled=current===0;$('next').disabled=current===12;$('progress-fill').style.width=`${Math.min(current+1,12)/12*100}%`;if(hash)history.replaceState(null,'',`#slide-${current+1}`);}
 function readHash(){const m=location.hash.match(/^#slide-(\d+)$/);show(m?Number(m[1])-1:0,false)}
 function toggle(id,button){$(id).hidden=!$(id).hidden;$(button).setAttribute('aria-expanded',String(!$(id).hidden))}
 $('previous').onclick=()=>show(current-1);$('next').onclick=()=>show(current+1);
 $('notes-toggle').onclick=()=>toggle('speaker-notes','notes-toggle');$('overview-toggle').onclick=()=>toggle('overview','overview-toggle');
 $('fullscreen-toggle').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen()}catch{$('fullscreen-toggle').textContent='전체 화면 사용 불가'}};
 slides.forEach((s,i)=>{const b=document.createElement('button');const n=document.createElement('span');n.textContent=String(i+1).padStart(2,'0');b.append(n,document.createTextNode(s.dataset.title));b.onclick=()=>{show(i);$('overview').hidden=true;$('overview-toggle').setAttribute('aria-expanded','false')};$('overview').append(b)});
 document.addEventListener('keydown',e=>{if(e.target.closest('button,a,input,textarea,select'))return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(current+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(current-1)}else if(e.key==='Home'){e.preventDefault();show(0)}else if(e.key==='End'){e.preventDefault();show(12)}else if(e.key.toLowerCase()==='n')$('notes-toggle').click();else if(e.key.toLowerCase()==='o')$('overview-toggle').click();else if(e.key.toLowerCase()==='f')$('fullscreen-toggle').click()});
 const events=[['처음의 질문','작업을 반복하고, 팀의 지식을 이어 쓰자','Pi 기반 loop 구상에서 협업·LLM Wiki 방향을 논의했습니다.','JOB-1 · JOB-38'],['방향을 구체화','터미널 TUI와 목적별 모델 선택으로','Pi TUI를 직접 재사용하고, 선택 정책과 실행 기록을 연결했습니다.','1f2eb36 · a8f2f77 · d66af14'],['MVP 실행 흐름','진단부터 작업 실행까지, 명령으로 연결','재현 가능한 fixture, 설정·진단, TUI 명령 흐름을 구현했습니다.','416c7e6 · 1e102cb · ac0f0cd'],['이어 쓰는 작업','승인한 지식 재사용과 중단 후 복구','Knowledge 재사용·상태 복구·한국어 온보딩 구현이 이어졌습니다.','1feef1e · 559da01 · e47f6d6']];
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{const v=events[Number(b.dataset.history)];['history-label','history-title','history-copy','history-source'].forEach((id,i)=>$(id).textContent=v[i]);document.querySelectorAll('[data-history]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
 const actions=['현재 단계와 승인된 입력을 확인해 Claude를 실행','산출물·요구사항·이전 지적을 DDT에 전달해 검토 요청','원문과 수정 대응을 대조하고, 보완 또는 다음 작업으로 연결'];
 document.querySelectorAll('[data-loop]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.loop);$('loop-action').textContent=actions[n];document.querySelectorAll('[data-loop]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));[0,1,2].forEach(i=>$('actor-'+i).classList.toggle('active',n===i))});
 document.querySelectorAll('[data-image]').forEach(b=>b.onclick=()=>{const before=b.dataset.image==='before';$('tui-image').src=before?'assets/windows-tui-before.png':'assets/windows-tui-fixed.png';$('tui-image').alt=before?'실제 Windows TUI 수정 전 캡처. 반복 출력에 들여쓰기가 누적되고 설정 안내가 남아 있는 화면.':'실제 Windows TUI 수정 후 캡처. 설정, 진단, 작업 생성과 목록 명령 화면.';document.querySelectorAll('[data-image]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)))});
 let touchX=null;$('viewport').addEventListener('touchstart',e=>{if(!e.target.closest('button,a'))touchX=e.changedTouches[0].clientX},{passive:true});$('viewport').addEventListener('touchend',e=>{if(touchX===null)return;const d=e.changedTouches[0].clientX-touchX;touchX=null;if(Math.abs(d)>60)show(current+(d<0?1:-1))},{passive:true});
 window.addEventListener('hashchange',readHash);readHash();
})();
