"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";

type Task = { id: string; title: string; status: string; runs: number };
type Run = { id: string; taskId: string; status: string; prompt: string; result?: string };
type View = "workspace" | "history" | "knowledge" | "skills" | "settings";

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>([]), [activeId, setActiveId] = useState<string | null>(null), [prompt, setPrompt] = useState(""), [runs, setRuns] = useState<Run[]>([]), [busy, setBusy] = useState(false), [view, setView] = useState<View>("workspace"), [message, setMessage] = useState("로컬 격리 샌드박스 가동 중");
  const active = useMemo(() => tasks.find((task) => task.id === activeId) ?? null, [tasks, activeId]);
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem("mindcraft-web-state") ?? "null"); if (saved?.tasks) setTasks(saved.tasks); if (saved?.activeId) setActiveId(saved.activeId); if (saved?.runs) setRuns(saved.runs); } catch { setMessage("저장된 작업을 불러오지 못했습니다."); } }, []);
  useEffect(() => { localStorage.setItem("mindcraft-web-state", JSON.stringify({ tasks, activeId, runs })); }, [tasks, activeId, runs]);

  function newTask() { const title = window.prompt("작업 제목을 입력하세요", "새 작업")?.trim(); if (!title) return; const task = { id: crypto.randomUUID(), title, status: "active", runs: 0 }; setTasks((items) => [...items, task]); setActiveId(task.id); setRuns([]); setView("workspace"); setMessage(`작업 공간 · ${title}`); }
  async function run(event: FormEvent) { event.preventDefault(); const value = prompt.trim(); if (!value || busy) return; let task = active; if (!task) { task = { id: crypto.randomUUID(), title: "새 작업", status: "active", runs: 0 }; setTasks([task]); setActiveId(task.id); } const runItem: Run = { id: crypto.randomUUID(), taskId: task.id, status: /\b(write|파일|삭제|명령|command)\b/iu.test(value) ? "approval_pending" : "running", prompt: value }; setBusy(true); setRuns((items) => [runItem, ...items]); setMessage(runItem.status === "approval_pending" ? "승인 대기 중" : "에이전트 실행 중"); await new Promise((resolve) => setTimeout(resolve, 350)); let result = ""; try { const response = await fetch("/api/run", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ taskId: task.id, prompt: value }) }); if (!response.ok) { const failure = await response.json().catch(() => ({})) as { error?: string }; throw new Error(failure.error ?? `HTTP ${response.status}`); } result = (await response.json() as { result?: string }).result ?? "Ollama Cloud 결과 없음"; } catch (error) { result = `오류 · ${error instanceof Error ? error.message : "Ollama Cloud 요청 실패"}`; setMessage("Ollama Cloud 연결 실패"); } if (runItem.status === "approval_pending") { setMessage("승인 대기 중 · Workflow에서 선택하세요"); } else { setRuns((items) => items.map((item) => item.id === runItem.id ? { ...item, status: "completed", result } : item)); setMessage("로컬 격리 샌드박스 가동 중"); } setTasks((items) => items.map((item) => item.id === task!.id ? { ...item, runs: item.runs + 1 } : item)); setPrompt(""); setBusy(false); }
  async function decideApproval(item: Run, decision: "approve" | "reject") { const response = await fetch("/api/approvals", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ runId: item.id, decision, prompt: item.prompt }) }); const payload = await response.json() as { status?: string; result?: string; error?: string }; if (!response.ok) { setMessage(payload.error ?? "승인 처리 실패"); return; } setRuns((items) => items.map((run) => run.id === item.id ? { ...run, status: payload.status ?? "rejected", result: payload.result } : run)); setMessage(decision === "approve" ? "승인 완료 · Workflow 실행" : "거부 완료 · 실행하지 않음"); }
  function selectTask(task: Task) { setActiveId(task.id); setRuns([]); setView("workspace"); setMessage(`작업 선택됨 · ${task.title}`); }
  const pipeline = ["요청 수신", "Knowledge 확인", "Agent 실행", "검토 및 승인", "결과 저장"];
  const latest = runs[0]; const completed = latest?.status === "completed"; const pending = latest?.status === "approval_pending";

  return <main className="dui-shell">
    <header className="topbar"><div className="window-controls"><i/><i/><i/></div><nav className="breadcrumb"><b>MindCraft<span>.</span></b><em>›</em><span>{view === "workspace" ? "작업 공간" : view === "history" ? "작업 기록" : view === "knowledge" ? "자료함" : view === "skills" ? "에이전트 스킬" : "AI 연결 설정"}</span></nav><div className="global-search">⌕<input placeholder="지식 규칙 및 승인 문서 검색..." onKeyDown={(event) => { if (event.key === "Enter") { setView("knowledge"); setMessage(`Knowledge 검색 · ${(event.target as HTMLInputElement).value}`); } }} /><kbd>⌘K</kbd></div><div className="top-actions"><span className="sandbox-dot">● <label>로컬 격리 샌드박스 가동 중</label></span><button title="새로고침" onClick={() => window.location.reload()}>↻</button><button className="avatar">K</button></div></header>
    <div className="dui-body">
      <aside className="sidebar"><div className="side-brand"><div className="brand-mark">◉</div><div><b>MindCraft<span>.</span></b><small>생각이 자라는 작업실</small></div></div><button className="new-task" onClick={newTask}><strong>＋</strong> 새 작업 시작 <kbd>⌘N</kbd></button><div className="nav-list"><button className={view === "workspace" ? "active" : ""} onClick={() => setView("workspace")}>⌂ <span>내 작업실</span></button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}>◷ <span>작업 기록</span></button><button className={view === "knowledge" ? "active" : ""} onClick={() => setView("knowledge")}>▤ <span>자료함 (지식)</span><small>48문서</small></button><button className={view === "skills" ? "active" : ""} onClick={() => setView("skills")}>✦ <span>에이전트 스킬</span><small>8개</small></button></div><div className="task-section"><div className="section-label">이어갈 작업 <span>(TASKS)</span><small>{tasks.length}건</small></div>{tasks.map((task) => <button key={task.id} className={`task-item ${activeId === task.id ? "selected" : ""}`} onClick={() => selectTask(task)}><b>● {task.title}</b><small>{task.status} · {task.id.slice(0, 8)}</small></button>)}{!tasks.length && <p>아직 작업이 없습니다.</p>}</div><button className="settings-link" onClick={() => setView("settings")}>⚙ 설정</button></aside>
      <section className="canvas">{view === "workspace" && <><div className="canvas-inner"><div className="welcome-icon">✧</div><h1>{active?.title ?? "무엇을 도와드릴까요?"}</h1><p className="welcome-copy">사내 지식 기반 자동화와 안전 실행 에이전트가 검증된 규칙을 준수하여 편안하게 답변을 정리합니다.</p>{runs.length > 0 && <div className="transcript">{runs.map((item) => <article key={item.id}><div><b>요청</b><small>{item.status} · {item.id.slice(0, 8)}</small></div><p>{item.prompt}</p>{item.result && <div className="answer">{item.result}</div>}{item.status === "approval_pending" && <div className="approval-actions"><span>이 작업은 승인이 필요합니다.</span><button onClick={() => void decideApproval(item, "approve")}>승인</button><button onClick={() => void decideApproval(item, "reject")}>거부</button></div>}</article>)}</div>}<form className="prompt-card" onSubmit={run}><div className="prompt-result">{latest?.result}</div><textarea value={prompt} onChange={(event) => setPrompt(event.target.value)} placeholder="AI 에이전트에게 지시하거나 질문하세요... (예: 지식베이스 규칙을 준수하여 문서를 작성해 줘)" rows={3} /><div className="prompt-tools"><span>⌘ <b>Agent</b> · mock-local</span><span>Enter 실행 · Shift+Enter 줄바꿈</span><button disabled={busy}>{busy ? "실행 중…" : "에이전트 실행 →"}</button></div></form></div></>}{view === "history" && <Page title="작업 기록" subtitle="Task별 실행 기록과 conversation을 확인합니다."><div className="record-list">{runs.length ? runs.map((item) => <article key={item.id}><b>{item.prompt}</b><span>{item.status}</span><p>{item.result ?? "실행 중인 작업입니다."}</p></article>) : <div className="empty-page">아직 실행 기록이 없습니다.</div>}</div></Page>}{view === "knowledge" && <Page title="자료함 (지식)" subtitle="검증된 규칙과 승인 문서를 관리합니다."><div className="info-card"><b>Knowledge workspace</b><p>검색창에서 규칙과 승인 문서를 검색하면 결과가 이 화면에 표시됩니다.</p><span>promoted 48문서 · candidate 검토 0건</span></div></Page>}{view === "skills" && <Page title="에이전트 스킬" subtitle="작업에 사용할 수 있는 안전한 Agent capability입니다."><div className="skill-grid">{["문서 분석", "Knowledge 검색", "요약 및 재작성", "파일 점검", "승인 workflow", "구조화된 답변", "Run 복원", "안전 정책 검사"].map((skill) => <div key={skill}>✦<b>{skill}</b><small>사용 가능 · 정책 적용</small></div>)}</div></Page>}{view === "settings" && <Page title="AI 연결 설정" subtitle="credential 원문을 UI에 저장하지 않는 안전한 연결 설정입니다."><div className="info-card"><label>Provider<input value="ollama" readOnly /></label><label>Model<input value="glm-5.3-flash:cloud" readOnly /></label><label>Endpoint<input value="https://ollama.com/v1" readOnly /></label><button className="dark-button" onClick={async () => { const response = await fetch("/api/run"); const status = await response.json() as { status?: string }; setMessage(status.status === "configured" ? "Ollama Cloud 연결 설정됨" : "Ollama Cloud credential missing"); }}>연결 상태 점검</button></div></Page>}</section>
      <aside className="pipeline"><div className="pipeline-head"><div><p>LIVE PIPELINE</p><h2>Workflow</h2></div><span className="live">● LIVE</span></div><div className="pipeline-task">{active?.title ?? "새 작업 대기 중"}<small>{latest ? `${latest.status} · ${latest.id.slice(0, 8)}` : "Prompt를 입력하면 시작됩니다"}</small></div>{pipeline.map((step, index) => { const done = completed || (!pending && latest && index < 3) || (pending && index < 3); return <div className={`pipeline-step ${done ? "done" : ""}`} key={step}><i>{done ? "✓" : index + 1}</i><div><b>{step}</b><small>{done ? "완료" : pending && index === 3 ? "승인 대기" : "대기"}</small></div></div>; })}<div className="pipeline-foot"><span>MODEL</span><b>glm-5.3-flash:cloud</b><span>STATUS</span><b>{message}</b></div></aside>
    </div>
  </main>;
}
function Page({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <div className="subpage"><p className="eyebrow">MINDCRAFT / CONSOLE</p><h1>{title}</h1><p>{subtitle}</p>{children}</div>; }
